@extends('layouts.app')

@section('title', 'PIN Checker')

@push('styles')
    <link rel="stylesheet" href="{{ asset('css/forms-custom.css') }}">
@endpush

@section('content')
<div id="formSectionContainer">
    <div class="mandatory-notice">
        All fields marked with <span class="required-star">*</span> are mandatory
    </div>

    <div class="form-container">
        <div class="form-header-banner">
            PIN Checker
        </div>

        <div class="form-body form-body-padded">
            <div class="form-description">
                The PIN Checker allows you to confirm whether or not a particular PIN is genuine. A genuine PIN is generated by the KRA - Domestic Taxes Department System and is in Active status. The Information provided by the PIN Checker is limited to basic details of the taxpayer.
            </div>
            
            <div class="section-group">
                <div class="section-group-title">Consult PIN Details</div>
                <table class="inner-profile-table">
                    <tbody>
                        <tr>
                            <td class="label-cell">PIN<span class="required-star">*</span></td>
                            <td class="input-cell">
                                <input type="text" class="form-input-custom" required>
                            </td>
                        </tr>
                        <tr>
                            <td class="label-cell">Security Stamp<span class="required-star">*</span></td>
                            <td class="input-cell">
                                <div class="search-filter-row-custom">
                                    <div onclick="refreshStamp()" style="cursor: pointer;">
                                        <i class="fas fa-sync-alt" style="color: #4CAF50; display: block;"></i>
                                    </div>
                                    <span id="stampQuestion" style="color: red; font-weight: bold; font-size: 1.1rem;"></span>
                                    <input type="text" class="form-input-custom" style="width: 80px; background: #f0f0f0;" required>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            
            <div class="btn-row">
                <button type="submit" class="btn-custom btn-submit-orange">Consult</button>
                <button type="button" class="btn-custom btn-primary-blue" onclick="window.location.href='{{ route('dashboard') }}'">Home</button>
                <button type="button" class="btn-custom btn-cancel-red" onclick="window.location.reload()">Reset</button>
            </div>
        </div>
    </div>
</div>

@push('scripts')
<script>
    document.addEventListener('DOMContentLoaded', function() {
        refreshStamp();
    });

    function refreshStamp() {
        const n1 = Math.floor(Math.random() * 100) + 10;
        const n2 = Math.floor(Math.random() * 10) + 1;
        const isAddition = Math.random() > 0.5;
        const question = isAddition ? `${n1} + ${n2} ?` : `${n1} - ${n2} ?`;
        document.getElementById('stampQuestion').innerText = question;
    }
</script>
@endpush
@endsection



